export const LOAD_BUY_LISTINGS_SUCCESS = 'LOAD_BUY_LISTINGS_SUCCESS';
export const LOAD_BUYER_ORDERS_SUCCESS = 'LOAD_BUYER_ORDERS_SUCCESS';
export const LOAD_SELLER_ORDERS_SUCCESS = 'LOAD_SELLER_ORDERS_SUCCESS';
export const LOAD_ETHPRICE_SUCCESS = 'LOAD_ETHPRICE_SUCCESS';
export const LOAD_MARKETINSTANCE_SUCCESS = 'LOAD_MARKETINSTANCE_SUCCESS';
export const LOAD_SELL_LISTINGS_SUCCESS = 'LOAD_SELL_LISTINGS_SUCCESS';
export const LOAD_USER_ADDRESS_SUCCESS = 'LOAD_USER_ADDRESS_SUCCESS';

