export const LOAD_LISTINGS_SUCCESS = 'LOAD_LISTINGS_SUCCESS';
export const LOAD_BUYER_ORDERS_SUCCESS = 'LOAD_BUYER_ORDERS_SUCCESS';
export const LOAD_SELLER_ORDERS_SUCCESS = 'LOAD_SELLER_ORDERS_SUCCESS';
